default: &default
  adapter: postgresql
  encoding: unicode
  database: dsbn-resource-booking-dev
  username: postgres
  password: beans
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# To setup rails, install and configure postgres, then run:
# rails db:setup and/or rails db:create
# then run rails db:migrate
production:
  <<: *default
  database: dsbn-resource-booking-dev
  username: postgres
  password: beans # Replace this with the password you set in postgres setup
  host: 127.0.0.1

test:
  <<: *default
  database: dsbn-resource-booking-test
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: srv-captain--dsbn-postgres
  port: 5432

development:
  <<: *default
  database: dsbn-resource-booking
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: srv-captain--dsbn-postgres
  port: 5432
