version: '3.5'
services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - BUILD_USER=${BUILD_USER}
        - NODE_ENV=${NODE_ENV}
    command: ['yarn', 'run', 'dev']
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - '.:/var/www/dsbnbooking.com'
      - node_modules:/var/www/dsbnbooking.com/node_modules/
    ports:
      - 4000:5173

volumes:
  node_modules: