services:
  frontend:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ./docker/entrypoints/frontend.sh
    env_file: .env.local
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      NODE_ENV: development
