version: '3.5'
services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ['yarn', 'run', 'vite']
    tty: true
    stdin_open: true
    volumes:
      - '.:/var/www/dsbnbooking.com'
      - node_modules:/var/www/dsbnbooking.com/node_modules/
    ports:
      - 4000:5173
    environment:
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: