version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails db:migrate RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/simcoesignout/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simcoesignout
      POSTGRES_DB: dsbn-resource-booking-dev

  frontend:
    tty: true
    entrypoint: bash -c "yarn run dev"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  postgres_data: